---
title: "Lecture 09 Homework Framework"
author: "Nathan Cobb"
date: "10/31/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse) # loads the tidyverse tools
library(DBI) # loads our database interface
library(RPostgres) # loads the database driver for PostgreSQL
library(connections) # helps RPostgres work with RStudio


# Normally we would use `DBI::dbConnect` here, but the `RPostgres` library
# doesn't integrate with the RStudio connections pane. This works around that fact.
# If you use `odbc` then you don't need this. 
con <- connection_open(RPostgres::Postgres(),
          dbname = "syntheticmguh",
          host = "35.199.26.47",
          user = "hids502_student",
          password = "pursuit-parson-trivial",
          # Tell the driver to return very large integers as floating point (vs truncating them)
          bigint = "numeric")
```

# SyntheticMGUH Registry

A clinician has collected a series of patients that they will to work with other researchers on. This collection was derived from an EMR and is present in the SyntheticMGUH database as a table called `inpatientregistry` (technically a view). 

* [NIH PHI Review](https://privacyruleandresearch.nih.gov/pr_08.asp#8a) - Includes the 18 elements

They have placed their registry in your regulard database in a table called `inpatientregistry`. Note that it contains columns that are identifiers, and columns that are not. *Your homework report should not contain any identifiers. You will be docked points if it does.*

```{sql connection=con}
-- Note that you should delete this section, its just an example
-- SELECT * FROM inpatientregistry LIMIT 5
```

# Fully De-identified Table

Create and return a data set that is fully de-identified.

 * Include all dates 'date shifted'
 * Include the age at the time of admission and age at the date of death (from the original dates)
 * Include as much of the data as possible, without violating HIPAA!

Build a patient lookup table. Note that we should probably randomize the order of the MRNs to make sure that our new ones and the old ones aren't in synch. This happens naturally here, but normally it would be best practice.

```{sql connection=con}
DROP TABLE IF EXISTS patient_lookup
```

```{sql connection=con}
-- We only want one row per MRN!!
WITH distinct_mrns AS (
  SELECT DISTINCT medical_record_id FROM inpatientregistry
)
SELECT 
  medical_record_id,
  10000 + row_number() OVER () as new_mrn,
  365 + cast(random() * 365 as INT) as date_shift_offset
INTO TEMP TABLE patient_lookup
FROM distinct_mrns
```
Build an encounter lookup table
```{sql connection=con}
DROP TABLE IF EXISTS encounter_lookup
```
```{sql connection=con}
-- In theory we only have one row per encounter, so we don't need the
-- extra step of enforcing DISTINCT ... but we probably should have checked that
-- first!
SELECT 
  encounter_id,
  100000 + 2 * (row_number() OVER ()) as new_encounter_id
INTO TEMP TABLE encounter_lookup
FROM inpatientregistry
```
Here is our full deidentified table

```{sql connection=con}
SELECT new_mrn, new_encounter_id, 
   CASE WHEN date_part('year', age(admission_date, birthdate)) >= 90 THEN 90 
     ELSE date_part('year', age(admission_date, birthdate)) END as age_at_admission,
   admission_date + date_shift_offset as admission_date_shifted,
   discharge_date + date_shift_offset as discharge_date_shifted,
   CASE WHEN date_part('year', age(deathdate, birthdate)) >= 90 THEN 90 
     ELSE date_part('year', age(deathdate, birthdate)) END as age_at_death,
   race, ethnicity, gender, state,
   code, description, reasoncode, reasondescription
FROM inpatientregistry
LEFT JOIN patient_lookup ON patient_lookup.medical_record_id = inpatientregistry.medical_record_id
LEFT JOIN encounter_lookup ON encounter_lookup.encounter_id = inpatientregistry.encounter_id
```

We can also do this in one pass without the lookup tables:
```{sql connection=con}
DROP TABLE IF EXISTS inpatientregistry_hipaa
```
```{sql connection=con}
-- Use a CTE to make sure we have a single random number to use across the entire row 
-- if we execute random() multiple times we will get multiple results
WITH distinct_mrns AS (
  SELECT DISTINCT medical_record_id FROM inpatientregistry
),
patient_offsets AS (
  SELECT medical_record_id, 365 + CAST(random() * 365 as INT) as date_shift_offset
  FROM distinct_mrns
)
SELECT 
   md5(CAST(inpatientregistry.medical_record_id AS VARCHAR)) as new_mrn,
   md5(CAST(encounter_id AS VARCHAR)) as new_encounter_id,
   CASE WHEN date_part('year', age(admission_date, birthdate)) >= 90 THEN 90 
     ELSE date_part('year', age(admission_date, birthdate)) END as age_at_admission,
   admission_date + date_shift_offset as admission_date_shifted,
   discharge_date + date_shift_offset as discharge_date_shifted,
   CASE WHEN date_part('year', age(deathdate, birthdate)) >= 90 THEN 90 
     ELSE date_part('year', age(deathdate, birthdate)) END as age_at_death,
   race, ethnicity, gender, state,
   code, description, reasoncode, reasondescription
INTO TEMP TABLE inpatientregistry_hipaa
FROM inpatientregistry
LEFT JOIN patient_offsets ON patient_offsets.medical_record_id = inpatientregistry.medical_record_id
```
```{sql connection=con}
SELECT * FROM inpatientregistry_hipaa
```
# Limited Data Set Table

Create and return a data set that is de-identified to HIPAA standards. Technically you can return a date of birth, but generally there is no good reason to do so (unless its a pediatric patient).
```{sql connection=con}
DROP TABLE IF EXISTS inpatientregistry_hipaa_limited
```
```{sql connection=con}
WITH distinct_mrns AS (
  SELECT DISTINCT medical_record_id FROM inpatientregistry
),
patient_offsets AS (
  SELECT medical_record_id, 365 + CAST(random() * 365 as INT) as date_shift_offset
  FROM distinct_mrns
)
SELECT 
   md5(CAST(inpatientregistry.medical_record_id AS VARCHAR)) as new_mrn,
   md5(CAST(encounter_id AS VARCHAR)) as new_encounter_id,
   CASE WHEN date_part('year', age(admission_date, birthdate)) >= 90 THEN 90 
     ELSE date_part('year', age(admission_date, birthdate)) END as age_at_admission,
   admission_date,
   discharge_date,
   deathdate,
   race, ethnicity, gender, 
   city, state, county, zip,
   code, description, reasoncode, reasondescription
INTO TEMP TABLE inpatientregistry_hipaa_limited
FROM inpatientregistry
LEFT JOIN patient_offsets ON patient_offsets.medical_record_id = inpatientregistry.medical_record_id
```
```{sql connection=con}
SELECT * FROM inpatientregistry_hipaa_limited
```

# Demonstrate Equivilence

Show that the 3 tables are equivilent, that we have not lost or corrupted any data in the process. At the minumum, show that you have the same number of unique identifiers (in other words, your deidentified results have the exact same number of patients as the original table.)
```{sql connection=con}
SELECT 
  'inpatientregistry' as table,  
  COUNT(*) AS rows, COUNT(DISTINCT medical_record_id) AS patients, COUNT(DISTINCT encounter_id) AS encounters
FROM inpatientregistry
UNION
SELECT 
 'inpatientregistry_hipaa' as table, 
 COUNT(*) AS rows, COUNT(DISTINCT new_mrn) AS patients, COUNT(DISTINCT new_encounter_id) AS encounters
 FROM inpatientregistry_hipaa
UNION
SELECT 
  'inpatientregistry_hipaa_limited' as table,
  COUNT(*) AS rows, COUNT(DISTINCT new_mrn) AS patients, COUNT(DISTINCT new_encounter_id) AS encounters
  FROM inpatientregistry_hipaa_limited
```
